// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getuserauth/getuserauth.proto

/*
Package go_micro_srv_GetUserAuth is a generated protocol buffer package.

It is generated from these files:
	proto/getuserauth/getuserauth.proto

It has these top-level messages:
	Request
	Response
*/
package go_micro_srv_GetUserAuth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GetUserAuth service

type GetUserAuthService interface {
	GetUserAuth(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type getUserAuthService struct {
	c    client.Client
	name string
}

func NewGetUserAuthService(name string, c client.Client) GetUserAuthService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.GetUserAuth"
	}
	return &getUserAuthService{
		c:    c,
		name: name,
	}
}

func (c *getUserAuthService) GetUserAuth(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetUserAuth.GetUserAuth", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetUserAuth service

type GetUserAuthHandler interface {
	GetUserAuth(context.Context, *Request, *Response) error
}

func RegisterGetUserAuthHandler(s server.Server, hdlr GetUserAuthHandler, opts ...server.HandlerOption) error {
	type getUserAuth interface {
		GetUserAuth(ctx context.Context, in *Request, out *Response) error
	}
	type GetUserAuth struct {
		getUserAuth
	}
	h := &getUserAuthHandler{hdlr}
	return s.Handle(s.NewHandler(&GetUserAuth{h}, opts...))
}

type getUserAuthHandler struct {
	GetUserAuthHandler
}

func (h *getUserAuthHandler) GetUserAuth(ctx context.Context, in *Request, out *Response) error {
	return h.GetUserAuthHandler.GetUserAuth(ctx, in, out)
}
