// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/postret/postret.proto

package go_micro_srv_PostRet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	// 手机号
	Mobile string `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	// 密码
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	// 短信验证码
	SmsCode              string   `protobuf:"bytes,3,opt,name=SmsCode,proto3" json:"SmsCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ba78726f04069b3, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Request) GetSmsCode() string {
	if m != nil {
		return m.SmsCode
	}
	return ""
}

type Response struct {
	ErrNo                string   `protobuf:"bytes,1,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	SessionId            string   `protobuf:"bytes,3,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ba78726f04069b3, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrNo() string {
	if m != nil {
		return m.ErrNo
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.PostRet.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.PostRet.Response")
}

func init() { proto.RegisterFile("proto/postret/postret.proto", fileDescriptor_4ba78726f04069b3) }

var fileDescriptor_4ba78726f04069b3 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xad, 0x62, 0xb7, 0x9d, 0xe3, 0x50, 0x64, 0xa9, 0x7f, 0x90, 0x9c, 0x3c, 0xad, 0xa0,
	0x1f, 0x41, 0x72, 0x50, 0xa8, 0x94, 0x2d, 0xea, 0xb9, 0x35, 0x43, 0x08, 0x24, 0x99, 0x75, 0x66,
	0xfd, 0xf3, 0xf1, 0xc5, 0xcd, 0x46, 0x2f, 0xf6, 0x34, 0xfc, 0xde, 0x83, 0x37, 0xf3, 0x06, 0x4e,
	0x83, 0x70, 0xe4, 0xeb, 0xc0, 0x1a, 0x85, 0xe2, 0x38, 0x5d, 0x52, 0x71, 0x51, 0xb3, 0xeb, 0x9a,
	0x57, 0x61, 0xa7, 0xf2, 0xe1, 0xd6, 0xac, 0xd1, 0x53, 0x2c, 0x5e, 0xc0, 0x78, 0x7a, 0x7b, 0x27,
	0x8d, 0x78, 0x02, 0xd3, 0x15, 0xef, 0x9a, 0x96, 0xec, 0xe4, 0x72, 0x72, 0x35, 0xf7, 0x99, 0x70,
	0x09, 0xb3, 0xf5, 0x56, 0xf5, 0x93, 0xa5, 0xb2, 0x87, 0xc9, 0xf9, 0x65, 0xb4, 0x60, 0x36, 0x9d,
	0xde, 0x71, 0x45, 0xf6, 0x28, 0x59, 0x23, 0x16, 0xcf, 0x30, 0xf3, 0xa4, 0x81, 0x7b, 0x25, 0x5c,
	0xc0, 0x71, 0x29, 0xf2, 0xc8, 0x39, 0x78, 0x80, 0x9f, 0x7d, 0xa5, 0xc8, 0x4a, 0xeb, 0x9c, 0x9a,
	0x09, 0xcf, 0x60, 0xbe, 0x21, 0xd5, 0x86, 0xfb, 0xfb, 0x2a, 0xa7, 0xfe, 0x09, 0x37, 0x4f, 0x60,
	0xca, 0xaf, 0x6d, 0x17, 0x5a, 0xc2, 0x07, 0x30, 0xb9, 0x06, 0x9e, 0xbb, 0xff, 0xda, 0xb9, 0x5c,
	0x6d, 0x79, 0xb1, 0xcf, 0x1e, 0x0e, 0x2c, 0x0e, 0x76, 0xd3, 0xf4, 0xa4, 0xdb, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x8b, 0xd0, 0x45, 0xcb, 0x43, 0x01, 0x00, 0x00,
}
