// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getuserorder/getuserorder.proto

/*
Package go_micro_srv_GetUserOrder is a generated protocol buffer package.

It is generated from these files:
	proto/getuserorder/getuserorder.proto

It has these top-level messages:
	Request
	Response
*/
package go_micro_srv_GetUserOrder

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GetUserOrder service

type GetUserOrderService interface {
	GetUserOrder(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type getUserOrderService struct {
	c    client.Client
	name string
}

func NewGetUserOrderService(name string, c client.Client) GetUserOrderService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.GetUserOrder"
	}
	return &getUserOrderService{
		c:    c,
		name: name,
	}
}

func (c *getUserOrderService) GetUserOrder(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetUserOrder.GetUserOrder", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetUserOrder service

type GetUserOrderHandler interface {
	GetUserOrder(context.Context, *Request, *Response) error
}

func RegisterGetUserOrderHandler(s server.Server, hdlr GetUserOrderHandler, opts ...server.HandlerOption) error {
	type getUserOrder interface {
		GetUserOrder(ctx context.Context, in *Request, out *Response) error
	}
	type GetUserOrder struct {
		getUserOrder
	}
	h := &getUserOrderHandler{hdlr}
	return s.Handle(s.NewHandler(&GetUserOrder{h}, opts...))
}

type getUserOrderHandler struct {
	GetUserOrderHandler
}

func (h *getUserOrderHandler) GetUserOrder(ctx context.Context, in *Request, out *Response) error {
	return h.GetUserOrderHandler.GetUserOrder(ctx, in, out)
}
