// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/getuserorder/getuserorder.proto

package go_micro_srv_GetUserOrder

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=Role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c94d30410695cd, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Request) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type Response struct {
	ErrNo                string   `protobuf:"bytes,1,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Orders               []byte   `protobuf:"bytes,3,opt,name=Orders,proto3" json:"Orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c94d30410695cd, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrNo() string {
	if m != nil {
		return m.ErrNo
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetOrders() []byte {
	if m != nil {
		return m.Orders
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetUserOrder.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetUserOrder.Response")
}

func init() {
	proto.RegisterFile("proto/getuserorder/getuserorder.proto", fileDescriptor_13c94d30410695cd)
}

var fileDescriptor_13c94d30410695cd = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4f, 0x2d, 0x29, 0x2d, 0x4e, 0x2d, 0xca, 0x2f, 0x4a, 0x49, 0x2d, 0x42, 0xe1,
	0xe8, 0x81, 0xe5, 0x85, 0x24, 0xd3, 0xf3, 0xf5, 0x72, 0x33, 0x93, 0x8b, 0xf2, 0xf5, 0x8a, 0x8b,
	0xca, 0xf4, 0xdc, 0x53, 0x4b, 0x42, 0x8b, 0x53, 0x8b, 0xfc, 0x41, 0x0a, 0x94, 0xac, 0xb9, 0xd8,
	0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x64, 0xb8, 0x38, 0x83, 0x53, 0x8b, 0x8b, 0x33,
	0xf3, 0xf3, 0x3c, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x10, 0x02, 0x42, 0x42, 0x5c,
	0x2c, 0x41, 0xf9, 0x39, 0xa9, 0x12, 0x4c, 0x60, 0x09, 0x30, 0x5b, 0x29, 0x80, 0x8b, 0x23, 0x28,
	0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x84, 0x8b, 0xd5, 0xb5, 0xa8, 0xc8, 0x2f, 0x1f,
	0xaa, 0x13, 0xc2, 0x11, 0x12, 0xe3, 0x62, 0x73, 0x2d, 0x2a, 0xf2, 0x2d, 0x4e, 0x87, 0xea, 0x83,
	0xf2, 0x40, 0xe2, 0x60, 0xfb, 0x8b, 0x25, 0x98, 0x15, 0x18, 0x35, 0x78, 0x82, 0xa0, 0x3c, 0xa3,
	0x4c, 0x2e, 0x1e, 0x64, 0xe7, 0x09, 0x45, 0xa2, 0xf1, 0x95, 0xf4, 0x70, 0x7a, 0x45, 0x0f, 0xea,
	0x0f, 0x29, 0x65, 0xbc, 0x6a, 0x20, 0xce, 0x55, 0x62, 0x48, 0x62, 0x03, 0x87, 0x8d, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0xaa, 0x52, 0x83, 0xcc, 0x44, 0x01, 0x00, 0x00,
}
