// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/postuserauth/postuserauth.proto

/*
Package go_micro_srv_PostUserAuth is a generated protocol buffer package.

It is generated from these files:
	proto/postuserauth/postuserauth.proto

It has these top-level messages:
	Request
	Response
*/
package go_micro_srv_PostUserAuth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PostUserAuth service

type PostUserAuthService interface {
	PostUserAuth(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type postUserAuthService struct {
	c    client.Client
	name string
}

func NewPostUserAuthService(name string, c client.Client) PostUserAuthService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.PostUserAuth"
	}
	return &postUserAuthService{
		c:    c,
		name: name,
	}
}

func (c *postUserAuthService) PostUserAuth(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostUserAuth.PostUserAuth", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PostUserAuth service

type PostUserAuthHandler interface {
	PostUserAuth(context.Context, *Request, *Response) error
}

func RegisterPostUserAuthHandler(s server.Server, hdlr PostUserAuthHandler, opts ...server.HandlerOption) error {
	type postUserAuth interface {
		PostUserAuth(ctx context.Context, in *Request, out *Response) error
	}
	type PostUserAuth struct {
		postUserAuth
	}
	h := &postUserAuthHandler{hdlr}
	return s.Handle(s.NewHandler(&PostUserAuth{h}, opts...))
}

type postUserAuthHandler struct {
	PostUserAuthHandler
}

func (h *postUserAuthHandler) PostUserAuth(ctx context.Context, in *Request, out *Response) error {
	return h.PostUserAuthHandler.PostUserAuth(ctx, in, out)
}
