// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/postorders/postorders.proto

package go_micro_srv_PostOrders

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	SessionId string `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	// 提交的订单信息
	OrderInfo            []byte   `protobuf:"bytes,2,opt,name=OrderInfo,proto3" json:"OrderInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_195535c7b44124b8, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Request) GetOrderInfo() []byte {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

type Response struct {
	ErrNo  string `protobuf:"bytes,1,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// 订单 id
	OrderId              string   `protobuf:"bytes,3,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_195535c7b44124b8, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrNo() string {
	if m != nil {
		return m.ErrNo
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.PostOrders.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.PostOrders.Response")
}

func init() { proto.RegisterFile("proto/postorders/postorders.proto", fileDescriptor_195535c7b44124b8) }

var fileDescriptor_195535c7b44124b8 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xbf, 0x8e, 0x82, 0x40,
	0x10, 0x87, 0x8f, 0xbb, 0x1c, 0x1c, 0x93, 0xab, 0x36, 0x46, 0x37, 0xc6, 0x02, 0xa8, 0xa8, 0xd6,
	0x44, 0x9f, 0x81, 0x82, 0xc2, 0x3f, 0x59, 0x9e, 0x40, 0x65, 0x25, 0x14, 0x32, 0x38, 0xb3, 0xfa,
	0xfc, 0xc6, 0x05, 0x83, 0x16, 0xda, 0xed, 0x37, 0xdf, 0xce, 0x64, 0x7e, 0x03, 0x71, 0x4b, 0x68,
	0x71, 0xde, 0x22, 0x5b, 0xa4, 0xd2, 0x10, 0x3f, 0x3d, 0x95, 0x73, 0x62, 0x52, 0xa1, 0x3a, 0xd5,
	0x07, 0x42, 0xc5, 0x74, 0x55, 0x5b, 0x64, 0xbb, 0x71, 0x3a, 0xc9, 0x20, 0xd0, 0xe6, 0x7c, 0x31,
	0x6c, 0xc5, 0x0c, 0xc2, 0xc2, 0x30, 0xd7, 0xd8, 0xe4, 0xa5, 0xf4, 0x22, 0x2f, 0x0d, 0xf5, 0x50,
	0xb8, 0x5b, 0xd7, 0x92, 0x37, 0x47, 0x94, 0xdf, 0x91, 0x97, 0xfe, 0xeb, 0xa1, 0x90, 0x68, 0xf8,
	0xd3, 0x86, 0x5b, 0x6c, 0xd8, 0x88, 0x11, 0xfc, 0x66, 0x44, 0x6b, 0xec, 0x67, 0x74, 0x20, 0xc6,
	0xe0, 0x67, 0x44, 0x2b, 0xae, 0x5c, 0x73, 0xa8, 0x7b, 0x12, 0x12, 0x82, 0x6e, 0x4c, 0x29, 0x7f,
	0x9c, 0x78, 0xe0, 0x62, 0x07, 0x30, 0x2c, 0x2a, 0x8a, 0x17, 0x8a, 0xd4, 0x9b, 0x40, 0xaa, 0x4f,
	0x33, 0x8d, 0x3f, 0xfc, 0xe8, 0x16, 0x4d, 0xbe, 0xf6, 0xbe, 0xbb, 0xce, 0xf2, 0x16, 0x00, 0x00,
	0xff, 0xff, 0x1d, 0x7c, 0x27, 0x9d, 0x42, 0x01, 0x00, 0x00,
}
