// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/postorders/postorders.proto

/*
Package go_micro_srv_PostOrders is a generated protocol buffer package.

It is generated from these files:
	proto/postorders/postorders.proto

It has these top-level messages:
	Request
	Response
*/
package go_micro_srv_PostOrders

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PostOrders service

type PostOrdersService interface {
	PostOrders(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type postOrdersService struct {
	c    client.Client
	name string
}

func NewPostOrdersService(name string, c client.Client) PostOrdersService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.PostOrders"
	}
	return &postOrdersService{
		c:    c,
		name: name,
	}
}

func (c *postOrdersService) PostOrders(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostOrders.PostOrders", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PostOrders service

type PostOrdersHandler interface {
	PostOrders(context.Context, *Request, *Response) error
}

func RegisterPostOrdersHandler(s server.Server, hdlr PostOrdersHandler, opts ...server.HandlerOption) error {
	type postOrders interface {
		PostOrders(ctx context.Context, in *Request, out *Response) error
	}
	type PostOrders struct {
		postOrders
	}
	h := &postOrdersHandler{hdlr}
	return s.Handle(s.NewHandler(&PostOrders{h}, opts...))
}

type postOrdersHandler struct {
	PostOrdersHandler
}

func (h *postOrdersHandler) PostOrders(ctx context.Context, in *Request, out *Response) error {
	return h.PostOrdersHandler.PostOrders(ctx, in, out)
}
