// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/getarea/getarea.proto

package go_micro_srv_GetArea

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d385e7a61b644f, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	// 返回错误码
	ErrNo string `protobuf:"bytes,1,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	// 返回错误信息
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// 用自定义类型返回的数组
	Data                 []*Response_Area `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d385e7a61b644f, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrNo() string {
	if m != nil {
		return m.ErrNo
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetData() []*Response_Area {
	if m != nil {
		return m.Data
	}
	return nil
}

// 返回数据类型
type Response_Area struct {
	Aid                  int32    `protobuf:"varint,1,opt,name=Aid,proto3" json:"Aid,omitempty"`
	Aname                string   `protobuf:"bytes,2,opt,name=Aname,proto3" json:"Aname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Area) Reset()         { *m = Response_Area{} }
func (m *Response_Area) String() string { return proto.CompactTextString(m) }
func (*Response_Area) ProtoMessage()    {}
func (*Response_Area) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d385e7a61b644f, []int{1, 0}
}

func (m *Response_Area) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Area.Unmarshal(m, b)
}
func (m *Response_Area) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Area.Marshal(b, m, deterministic)
}
func (m *Response_Area) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Area.Merge(m, src)
}
func (m *Response_Area) XXX_Size() int {
	return xxx_messageInfo_Response_Area.Size(m)
}
func (m *Response_Area) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Area.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Area proto.InternalMessageInfo

func (m *Response_Area) GetAid() int32 {
	if m != nil {
		return m.Aid
	}
	return 0
}

func (m *Response_Area) GetAname() string {
	if m != nil {
		return m.Aname
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetArea.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetArea.Response")
	proto.RegisterType((*Response_Area)(nil), "go.micro.srv.GetArea.Response.Area")
}

func init() { proto.RegisterFile("proto/getarea/getarea.proto", fileDescriptor_28d385e7a61b644f) }

var fileDescriptor_28d385e7a61b644f = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4f, 0x2d, 0x49, 0x2c, 0x4a, 0x4d, 0x84, 0xd1, 0x7a, 0x60, 0x51, 0x21, 0x91,
	0xf4, 0x7c, 0xbd, 0xdc, 0xcc, 0xe4, 0xa2, 0x7c, 0xbd, 0xe2, 0xa2, 0x32, 0x3d, 0xf7, 0xd4, 0x12,
	0xc7, 0xa2, 0xd4, 0x44, 0x25, 0x4e, 0x2e, 0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0xa5,
	0x85, 0x8c, 0x5c, 0x1c, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x22, 0x5c, 0xac,
	0xae, 0x45, 0x45, 0x7e, 0xf9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x18,
	0x17, 0x9b, 0x6b, 0x51, 0x91, 0x6f, 0x71, 0xba, 0x04, 0x13, 0x58, 0x18, 0xca, 0x13, 0x32, 0xe7,
	0x62, 0x71, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x56, 0x60, 0xd6, 0xe0, 0x36, 0x52, 0xd6, 0xc3, 0x66,
	0x95, 0x1e, 0xcc, 0x6c, 0x3d, 0x10, 0x2f, 0x08, 0xac, 0x41, 0x4a, 0x8f, 0x8b, 0x05, 0xc4, 0x13,
	0x12, 0xe0, 0x62, 0x76, 0xcc, 0x4c, 0x01, 0x5b, 0xc6, 0x1a, 0x04, 0x62, 0x82, 0x1c, 0xe0, 0x98,
	0x97, 0x98, 0x9b, 0x0a, 0xb5, 0x09, 0xc2, 0x31, 0x0a, 0xe5, 0x62, 0x77, 0xad, 0x48, 0xcc, 0x2d,
	0xc8, 0x49, 0x15, 0xf2, 0xe2, 0x62, 0x87, 0x9a, 0x2c, 0x24, 0x8b, 0xcb, 0x42, 0xb0, 0xc7, 0xa4,
	0xe4, 0xf0, 0xbb, 0x47, 0x89, 0x21, 0x89, 0x0d, 0x1c, 0x44, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x09, 0x75, 0x7e, 0xdb, 0x41, 0x01, 0x00, 0x00,
}
