// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getsmscd/getsmscd.proto

/*
Package go_micro_srv_GetSmscd is a generated protocol buffer package.

It is generated from these files:
	proto/getsmscd/getsmscd.proto

It has these top-level messages:
	Request
	Response
*/
package go_micro_srv_GetSmscd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GetSmscd service

type GetSmscdService interface {
	GetSmscd(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type getSmscdService struct {
	c    client.Client
	name string
}

func NewGetSmscdService(name string, c client.Client) GetSmscdService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.GetSmscd"
	}
	return &getSmscdService{
		c:    c,
		name: name,
	}
}

func (c *getSmscdService) GetSmscd(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetSmscd.GetSmscd", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetSmscd service

type GetSmscdHandler interface {
	GetSmscd(context.Context, *Request, *Response) error
}

func RegisterGetSmscdHandler(s server.Server, hdlr GetSmscdHandler, opts ...server.HandlerOption) error {
	type getSmscd interface {
		GetSmscd(ctx context.Context, in *Request, out *Response) error
	}
	type GetSmscd struct {
		getSmscd
	}
	h := &getSmscdHandler{hdlr}
	return s.Handle(s.NewHandler(&GetSmscd{h}, opts...))
}

type getSmscdHandler struct {
	GetSmscdHandler
}

func (h *getSmscdHandler) GetSmscd(ctx context.Context, in *Request, out *Response) error {
	return h.GetSmscdHandler.GetSmscd(ctx, in, out)
}
