// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/getsmscd/getsmscd.proto

package go_micro_srv_GetSmscd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	// 手机号
	Mobile string `protobuf:"bytes,1,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	// 验证码
	Text string `protobuf:"bytes,2,opt,name=Text,proto3" json:"Text,omitempty"`
	// uuid
	Uuid                 string   `protobuf:"bytes,3,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_27966e22b83c4376, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Request) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	ErrNo                string   `protobuf:"bytes,1,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_27966e22b83c4376, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrNo() string {
	if m != nil {
		return m.ErrNo
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetSmscd.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetSmscd.Response")
}

func init() { proto.RegisterFile("proto/getsmscd/getsmscd.proto", fileDescriptor_27966e22b83c4376) }

var fileDescriptor_27966e22b83c4376 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4f, 0x2d, 0x29, 0xce, 0x2d, 0x4e, 0x4e, 0x81, 0x33, 0xf4, 0xc0, 0xe2, 0x42,
	0xa2, 0xe9, 0xf9, 0x7a, 0xb9, 0x99, 0xc9, 0x45, 0xf9, 0x7a, 0xc5, 0x45, 0x65, 0x7a, 0xee, 0xa9,
	0x25, 0xc1, 0x20, 0x49, 0x25, 0x4f, 0x2e, 0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21,
	0x31, 0x2e, 0x36, 0xdf, 0xfc, 0xa4, 0xcc, 0x9c, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x28, 0x4f, 0x48, 0x88, 0x8b, 0x25, 0x24, 0xb5, 0xa2, 0x44, 0x82, 0x09, 0x2c, 0x0a, 0x66, 0x83,
	0xc4, 0x42, 0x4b, 0x33, 0x53, 0x24, 0x98, 0x21, 0x62, 0x20, 0xb6, 0x92, 0x05, 0x17, 0x47, 0x50,
	0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x08, 0x17, 0xab, 0x6b, 0x51, 0x91, 0x5f, 0x3e,
	0xd4, 0x28, 0x08, 0x07, 0x64, 0x83, 0x6b, 0x51, 0x91, 0x6f, 0x71, 0x3a, 0xd4, 0x2c, 0x28, 0xcf,
	0x28, 0x92, 0x8b, 0x03, 0xe6, 0x20, 0x21, 0x5f, 0x24, 0xb6, 0x9c, 0x1e, 0x56, 0x47, 0xeb, 0x41,
	0x5d, 0x2c, 0x25, 0x8f, 0x53, 0x1e, 0xe2, 0x0c, 0x25, 0x86, 0x24, 0x36, 0xb0, 0xef, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xde, 0x3c, 0x59, 0xd6, 0x1e, 0x01, 0x00, 0x00,
}
