// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/getimagecd/getimagecd.proto

package go_micro_srv_GetImageCd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63873368ef8218e, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type Response struct {
	// 返回错误码
	ErrNo string `protobuf:"bytes,1,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	// 返回信息
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// 返回图片结构信息
	Pix                  []byte          `protobuf:"bytes,3,opt,name=Pix,proto3" json:"Pix,omitempty"`
	Stride               int64           `protobuf:"varint,4,opt,name=Stride,proto3" json:"Stride,omitempty"`
	Min                  *Response_Point `protobuf:"bytes,5,opt,name=Min,proto3" json:"Min,omitempty"`
	Max                  *Response_Point `protobuf:"bytes,6,opt,name=Max,proto3" json:"Max,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63873368ef8218e, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrNo() string {
	if m != nil {
		return m.ErrNo
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetPix() []byte {
	if m != nil {
		return m.Pix
	}
	return nil
}

func (m *Response) GetStride() int64 {
	if m != nil {
		return m.Stride
	}
	return 0
}

func (m *Response) GetMin() *Response_Point {
	if m != nil {
		return m.Min
	}
	return nil
}

func (m *Response) GetMax() *Response_Point {
	if m != nil {
		return m.Max
	}
	return nil
}

type Response_Point struct {
	X                    int64    `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    int64    `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_Point) Reset()         { *m = Response_Point{} }
func (m *Response_Point) String() string { return proto.CompactTextString(m) }
func (*Response_Point) ProtoMessage()    {}
func (*Response_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_e63873368ef8218e, []int{1, 0}
}

func (m *Response_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_Point.Unmarshal(m, b)
}
func (m *Response_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_Point.Marshal(b, m, deterministic)
}
func (m *Response_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_Point.Merge(m, src)
}
func (m *Response_Point) XXX_Size() int {
	return xxx_messageInfo_Response_Point.Size(m)
}
func (m *Response_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Response_Point proto.InternalMessageInfo

func (m *Response_Point) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Response_Point) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetImageCd.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetImageCd.Response")
	proto.RegisterType((*Response_Point)(nil), "go.micro.srv.GetImageCd.Response.Point")
}

func init() { proto.RegisterFile("proto/getimagecd/getimagecd.proto", fileDescriptor_e63873368ef8218e) }

var fileDescriptor_e63873368ef8218e = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4b, 0x33, 0x31,
	0x10, 0xc5, 0xbf, 0x7c, 0xe9, 0xae, 0x3a, 0xf6, 0x20, 0x83, 0x68, 0x28, 0x08, 0xe9, 0x7a, 0x70,
	0x4f, 0x11, 0xea, 0xc9, 0xb3, 0x14, 0xf1, 0x50, 0x29, 0x29, 0x42, 0x7b, 0x5c, 0xbb, 0x61, 0xc9,
	0xa1, 0x9b, 0x9a, 0xa4, 0xb2, 0xff, 0xbc, 0x20, 0x19, 0x57, 0xd4, 0x83, 0x8a, 0xb7, 0xf7, 0xcb,
	0xcc, 0x4b, 0xde, 0x64, 0x60, 0xbc, 0xf5, 0x2e, 0xba, 0xcb, 0xc6, 0x44, 0xbb, 0xa9, 0x1a, 0xb3,
	0xae, 0x3f, 0x49, 0x45, 0x35, 0x3c, 0x6d, 0x9c, 0xda, 0xd8, 0xb5, 0x77, 0x2a, 0xf8, 0x67, 0x75,
	0x6b, 0xe2, 0x5d, 0x2a, 0xdf, 0xd4, 0xc5, 0x19, 0xec, 0x69, 0xf3, 0xb4, 0x33, 0x21, 0x22, 0xc2,
	0xe0, 0x61, 0x67, 0x6b, 0xc1, 0x24, 0x2b, 0x0f, 0x34, 0xe9, 0xe2, 0x85, 0xc1, 0xbe, 0x36, 0x61,
	0xeb, 0xda, 0x60, 0xf0, 0x18, 0xb2, 0xa9, 0xf7, 0xf7, 0xae, 0xef, 0x78, 0x03, 0x3c, 0x81, 0x7c,
	0xea, 0xfd, 0x2c, 0x34, 0xe2, 0x3f, 0x1d, 0xf7, 0x84, 0x47, 0xc0, 0xe7, 0xb6, 0x13, 0x5c, 0xb2,
	0x72, 0xa8, 0x93, 0x4c, 0x9d, 0x8b, 0xe8, 0x6d, 0x6d, 0xc4, 0x40, 0xb2, 0x92, 0xeb, 0x9e, 0xf0,
	0x1a, 0xf8, 0xcc, 0xb6, 0x22, 0x93, 0xac, 0x3c, 0x9c, 0x5c, 0xa8, 0x6f, 0xa2, 0xaa, 0xf7, 0x1c,
	0x6a, 0xee, 0x6c, 0x1b, 0x75, 0xf2, 0x90, 0xb5, 0xea, 0x44, 0xfe, 0x57, 0x6b, 0xd5, 0x8d, 0xce,
	0x21, 0x23, 0xc2, 0x21, 0xb0, 0x25, 0x8d, 0xc4, 0x35, 0x5b, 0x26, 0x5a, 0xd1, 0x24, 0x5c, 0xb3,
	0xd5, 0xa4, 0x02, 0xf8, 0xb8, 0x06, 0x17, 0x5f, 0x48, 0xfe, 0xf0, 0x1c, 0xfd, 0xe8, 0x68, 0xfc,
	0x6b, 0xa0, 0xe2, 0xdf, 0x63, 0x4e, 0x1b, 0xba, 0x7a, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xaf,
	0x01, 0xb9, 0xc6, 0x01, 0x00, 0x00,
}
