// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/putcomment/putcomment.proto

/*
Package go_micro_srv_PutComment is a generated protocol buffer package.

It is generated from these files:
	proto/putcomment/putcomment.proto

It has these top-level messages:
	Request
	Response
*/
package go_micro_srv_PutComment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PutComment service

type PutCommentService interface {
	PutComment(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type putCommentService struct {
	c    client.Client
	name string
}

func NewPutCommentService(name string, c client.Client) PutCommentService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.PutComment"
	}
	return &putCommentService{
		c:    c,
		name: name,
	}
}

func (c *putCommentService) PutComment(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PutComment.PutComment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PutComment service

type PutCommentHandler interface {
	PutComment(context.Context, *Request, *Response) error
}

func RegisterPutCommentHandler(s server.Server, hdlr PutCommentHandler, opts ...server.HandlerOption) error {
	type putComment interface {
		PutComment(ctx context.Context, in *Request, out *Response) error
	}
	type PutComment struct {
		putComment
	}
	h := &putCommentHandler{hdlr}
	return s.Handle(s.NewHandler(&PutComment{h}, opts...))
}

type putCommentHandler struct {
	PutCommentHandler
}

func (h *putCommentHandler) PutComment(ctx context.Context, in *Request, out *Response) error {
	return h.PutCommentHandler.PutComment(ctx, in, out)
}
