// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/getuserinfo/getuserinfo.proto

package go_micro_srv_GetUserInfo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_db582ad9475e2ea6, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type Response struct {
	// 错误码
	ErrNo string `protobuf:"bytes,1,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	// 错误信息
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// 用户 id
	UserId int64 `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	// 用户名
	UserName string `protobuf:"bytes,4,opt,name=UserName,proto3" json:"UserName,omitempty"`
	// 手机号
	Mobile string `protobuf:"bytes,5,opt,name=Mobile,proto3" json:"Mobile,omitempty"`
	// 真实姓名
	RealName string `protobuf:"bytes,6,opt,name=RealName,proto3" json:"RealName,omitempty"`
	// 身份证号
	IdCard string `protobuf:"bytes,7,opt,name=IdCard,proto3" json:"IdCard,omitempty"`
	// 头像地址
	AvatarUrl            string   `protobuf:"bytes,8,opt,name=AvatarUrl,proto3" json:"AvatarUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_db582ad9475e2ea6, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrNo() string {
	if m != nil {
		return m.ErrNo
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Response) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Response) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *Response) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *Response) GetIdCard() string {
	if m != nil {
		return m.IdCard
	}
	return ""
}

func (m *Response) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetUserInfo.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetUserInfo.Response")
}

func init() {
	proto.RegisterFile("proto/getuserinfo/getuserinfo.proto", fileDescriptor_db582ad9475e2ea6)
}

var fileDescriptor_db582ad9475e2ea6 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xad, 0x48, 0x29, 0xeb, 0x6d, 0x63, 0xcc, 0x86, 0x78, 0xc0, 0x7a, 0x90, 0xd3, 0x9a,
	0xe8, 0x13, 0x18, 0x43, 0x4c, 0x0f, 0x70, 0x58, 0x83, 0xf7, 0xc5, 0x0e, 0x4d, 0x93, 0xd2, 0xc1,
	0x99, 0x85, 0x47, 0xf5, 0x79, 0xcc, 0xee, 0x56, 0xb4, 0x07, 0xb9, 0xcd, 0xf7, 0x77, 0xbe, 0x36,
	0xf3, 0x57, 0xdc, 0xed, 0x08, 0x1d, 0x3e, 0x54, 0xe0, 0xf6, 0x0c, 0x54, 0xb7, 0x9b, 0xde, 0xac,
	0xc3, 0x53, 0xa9, 0x2a, 0xd4, 0xdb, 0xfa, 0x83, 0x50, 0x33, 0x1d, 0xf4, 0x2b, 0xb8, 0x15, 0x03,
	0x15, 0xed, 0x06, 0xf3, 0x7b, 0x31, 0x32, 0xf0, 0xb9, 0x07, 0x76, 0xf2, 0x46, 0x8c, 0xdf, 0x80,
	0xb9, 0xc6, 0xb6, 0x28, 0x55, 0x32, 0x4d, 0x66, 0x63, 0xf3, 0x1b, 0xe4, 0x5f, 0x89, 0xc8, 0x0c,
	0xf0, 0x0e, 0x5b, 0x06, 0x79, 0x25, 0x86, 0x73, 0xa2, 0x25, 0x76, 0x6b, 0x11, 0xe4, 0xb5, 0x48,
	0xe7, 0x44, 0x0b, 0xae, 0xd4, 0x79, 0x88, 0x3b, 0xf2, 0x79, 0xf8, 0x5e, 0xa9, 0x06, 0xd3, 0x64,
	0x36, 0x30, 0x1d, 0xc9, 0x89, 0xc8, 0xfc, 0xb4, 0xb4, 0x5b, 0x50, 0x17, 0xc1, 0x38, 0xb2, 0x77,
	0x16, 0xb8, 0xae, 0x1b, 0x50, 0xc3, 0xf8, 0xae, 0x48, 0xde, 0x31, 0x60, 0x9b, 0xe0, 0xa4, 0xd1,
	0xf9, 0x61, 0xef, 0x14, 0xe5, 0x8b, 0xa5, 0x52, 0x8d, 0xa2, 0x13, 0xc9, 0x1f, 0xf6, 0x7c, 0xb0,
	0xce, 0xd2, 0x8a, 0x1a, 0x95, 0xc5, 0xc3, 0x8e, 0xc1, 0x23, 0x88, 0xcb, 0x3f, 0x85, 0xc8, 0xf7,
	0x3e, 0xde, 0xea, 0xff, 0xaa, 0xd3, 0x5d, 0x6f, 0x93, 0xfc, 0xd4, 0x4a, 0x2c, 0x2c, 0x3f, 0x5b,
	0xa7, 0xe1, 0x4f, 0x3c, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x26, 0x44, 0x21, 0x0c, 0xb0, 0x01,
	0x00, 0x00,
}
