// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/getuserinfo/getuserinfo.proto

/*
Package go_micro_srv_GetUserInfo is a generated protocol buffer package.

It is generated from these files:
	proto/getuserinfo/getuserinfo.proto

It has these top-level messages:
	Request
	Response
*/
package go_micro_srv_GetUserInfo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GetUserInfo service

type GetUserInfoService interface {
	GetUserInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type getUserInfoService struct {
	c    client.Client
	name string
}

func NewGetUserInfoService(name string, c client.Client) GetUserInfoService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.GetUserInfo"
	}
	return &getUserInfoService{
		c:    c,
		name: name,
	}
}

func (c *getUserInfoService) GetUserInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetUserInfo.GetUserInfo", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetUserInfo service

type GetUserInfoHandler interface {
	GetUserInfo(context.Context, *Request, *Response) error
}

func RegisterGetUserInfoHandler(s server.Server, hdlr GetUserInfoHandler, opts ...server.HandlerOption) error {
	type getUserInfo interface {
		GetUserInfo(ctx context.Context, in *Request, out *Response) error
	}
	type GetUserInfo struct {
		getUserInfo
	}
	h := &getUserInfoHandler{hdlr}
	return s.Handle(s.NewHandler(&GetUserInfo{h}, opts...))
}

type getUserInfoHandler struct {
	GetUserInfoHandler
}

func (h *getUserInfoHandler) GetUserInfo(ctx context.Context, in *Request, out *Response) error {
	return h.GetUserInfoHandler.GetUserInfo(ctx, in, out)
}
