// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/postlogin/postlogin.proto

/*
Package go_micro_srv_PostLogin is a generated protocol buffer package.

It is generated from these files:
	proto/postlogin/postlogin.proto

It has these top-level messages:
	Request
	Response
*/
package go_micro_srv_PostLogin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PostLogin service

type PostLoginService interface {
	PostLogin(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type postLoginService struct {
	c    client.Client
	name string
}

func NewPostLoginService(name string, c client.Client) PostLoginService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.PostLogin"
	}
	return &postLoginService{
		c:    c,
		name: name,
	}
}

func (c *postLoginService) PostLogin(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PostLogin.PostLogin", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PostLogin service

type PostLoginHandler interface {
	PostLogin(context.Context, *Request, *Response) error
}

func RegisterPostLoginHandler(s server.Server, hdlr PostLoginHandler, opts ...server.HandlerOption) error {
	type postLogin interface {
		PostLogin(ctx context.Context, in *Request, out *Response) error
	}
	type PostLogin struct {
		postLogin
	}
	h := &postLoginHandler{hdlr}
	return s.Handle(s.NewHandler(&PostLogin{h}, opts...))
}

type postLoginHandler struct {
	PostLoginHandler
}

func (h *postLoginHandler) PostLogin(ctx context.Context, in *Request, out *Response) error {
	return h.PostLoginHandler.PostLogin(ctx, in, out)
}
