// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/putuserinfo/putuserinfo.proto

/*
Package go_micro_srv_PutUserInfo is a generated protocol buffer package.

It is generated from these files:
	proto/putuserinfo/putuserinfo.proto

It has these top-level messages:
	Request
	Response
*/
package go_micro_srv_PutUserInfo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for PutUserInfo service

type PutUserInfoService interface {
	PutUserInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type putUserInfoService struct {
	c    client.Client
	name string
}

func NewPutUserInfoService(name string, c client.Client) PutUserInfoService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.PutUserInfo"
	}
	return &putUserInfoService{
		c:    c,
		name: name,
	}
}

func (c *putUserInfoService) PutUserInfo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "PutUserInfo.PutUserInfo", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PutUserInfo service

type PutUserInfoHandler interface {
	PutUserInfo(context.Context, *Request, *Response) error
}

func RegisterPutUserInfoHandler(s server.Server, hdlr PutUserInfoHandler, opts ...server.HandlerOption) error {
	type putUserInfo interface {
		PutUserInfo(ctx context.Context, in *Request, out *Response) error
	}
	type PutUserInfo struct {
		putUserInfo
	}
	h := &putUserInfoHandler{hdlr}
	return s.Handle(s.NewHandler(&PutUserInfo{h}, opts...))
}

type putUserInfoHandler struct {
	PutUserInfoHandler
}

func (h *putUserInfoHandler) PutUserInfo(ctx context.Context, in *Request, out *Response) error {
	return h.PutUserInfoHandler.PutUserInfo(ctx, in, out)
}
