// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/postavatar/postavatar.proto

package go_micro_srv_PostAvatar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	// sessionId
	SessionId string `protobuf:"bytes,1,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	// 二进制图片
	Avatar []byte `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	// 图片大小
	FileSize int64 `protobuf:"varint,3,opt,name=FileSize,proto3" json:"FileSize,omitempty"`
	// 图片名字
	FileName             string   `protobuf:"bytes,4,opt,name=FileName,proto3" json:"FileName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_9beebc3953b241b2, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Request) GetAvatar() []byte {
	if m != nil {
		return m.Avatar
	}
	return nil
}

func (m *Request) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *Request) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type Response struct {
	ErrNo                string   `protobuf:"bytes,1,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	ErrMsg               string   `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,3,opt,name=AvatarUrl,proto3" json:"AvatarUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_9beebc3953b241b2, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrNo() string {
	if m != nil {
		return m.ErrNo
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.PostAvatar.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.PostAvatar.Response")
}

func init() { proto.RegisterFile("proto/postavatar/postavatar.proto", fileDescriptor_9beebc3953b241b2) }

var fileDescriptor_9beebc3953b241b2 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x09, 0x85, 0xd2, 0x9c, 0x98, 0x2c, 0x04, 0x51, 0xc5, 0xe0, 0x66, 0xca, 0x64, 0x24,
	0x78, 0x02, 0x86, 0x22, 0x31, 0x50, 0x21, 0x47, 0xb0, 0x1b, 0x38, 0x55, 0x96, 0xda, 0x5e, 0xb8,
	0x33, 0x45, 0xe2, 0xe9, 0x51, 0x6d, 0x93, 0xc0, 0x40, 0xb7, 0x7c, 0xf7, 0xc7, 0xfe, 0xce, 0x3f,
	0xcc, 0x3a, 0xa6, 0x40, 0x57, 0x1d, 0x49, 0x70, 0x5b, 0x17, 0x1c, 0xff, 0xfa, 0x34, 0x31, 0x53,
	0x17, 0x4b, 0x32, 0x6b, 0xff, 0xca, 0x64, 0x84, 0xb7, 0xe6, 0x91, 0x24, 0xdc, 0xc6, 0xb8, 0xfe,
	0x84, 0x13, 0x8b, 0xef, 0x1f, 0x28, 0x41, 0x5d, 0x42, 0xd9, 0xa2, 0x88, 0xa7, 0xcd, 0xfd, 0x5b,
	0x55, 0xe8, 0xa2, 0x29, 0xed, 0x30, 0x50, 0xe7, 0x30, 0x4e, 0x47, 0xaa, 0x43, 0x5d, 0x34, 0xa7,
	0x36, 0x93, 0x9a, 0xc2, 0xe4, 0xce, 0xaf, 0xb0, 0xf5, 0x5f, 0x58, 0x8d, 0x74, 0xd1, 0x8c, 0x6c,
	0xcf, 0x3f, 0xd9, 0xc2, 0xad, 0xb1, 0x3a, 0x8a, 0x17, 0xf6, 0x5c, 0x3f, 0xc3, 0xc4, 0xa2, 0x74,
	0xb4, 0x11, 0x54, 0x67, 0x70, 0x3c, 0x67, 0x5e, 0x50, 0xb6, 0x26, 0xd8, 0x19, 0xe7, 0xcc, 0x0f,
	0xb2, 0x8c, 0xc6, 0xd2, 0x66, 0xda, 0xed, 0x99, 0xdc, 0x4f, 0xbc, 0x8a, 0xca, 0xd2, 0x0e, 0x83,
	0x6b, 0x07, 0x30, 0x3c, 0x4f, 0xb5, 0x7f, 0x48, 0x9b, 0x7f, 0x6a, 0x30, 0xb9, 0x83, 0xe9, 0x6c,
	0xcf, 0x1f, 0x69, 0xd9, 0xfa, 0xe0, 0x65, 0x1c, 0x3b, 0xbd, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0xc5, 0xf3, 0xe2, 0x95, 0x78, 0x01, 0x00, 0x00,
}
