// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gethouses/gethouses.proto

package go_micro_srv_GetHouses

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	// 地区编号
	AreaId string `protobuf:"bytes,1,opt,name=AreaId,proto3" json:"AreaId,omitempty"`
	// 起始日期
	StartDate string `protobuf:"bytes,2,opt,name=StartDate,proto3" json:"StartDate,omitempty"`
	// 结束日期
	EndDate string `protobuf:"bytes,3,opt,name=EndDate,proto3" json:"EndDate,omitempty"`
	// 查询方式
	SelectKey string `protobuf:"bytes,4,opt,name=SelectKey,proto3" json:"SelectKey,omitempty"`
	// 页码
	PageNumber           string   `protobuf:"bytes,5,opt,name=PageNumber,proto3" json:"PageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_637ed9c2c55ea129, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAreaId() string {
	if m != nil {
		return m.AreaId
	}
	return ""
}

func (m *Request) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *Request) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *Request) GetSelectKey() string {
	if m != nil {
		return m.SelectKey
	}
	return ""
}

func (m *Request) GetPageNumber() string {
	if m != nil {
		return m.PageNumber
	}
	return ""
}

type Response struct {
	ErrNo  string `protobuf:"bytes,1,opt,name=ErrNo,proto3" json:"ErrNo,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	// 房屋信息
	Houses []byte `protobuf:"bytes,3,opt,name=Houses,proto3" json:"Houses,omitempty"`
	// 当前页码
	CurrentPage int64 `protobuf:"varint,4,opt,name=CurrentPage,proto3" json:"CurrentPage,omitempty"`
	// 总页数
	TotalPage            int64    `protobuf:"varint,5,opt,name=TotalPage,proto3" json:"TotalPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_637ed9c2c55ea129, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrNo() string {
	if m != nil {
		return m.ErrNo
	}
	return ""
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetHouses() []byte {
	if m != nil {
		return m.Houses
	}
	return nil
}

func (m *Response) GetCurrentPage() int64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *Response) GetTotalPage() int64 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.GetHouses.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.GetHouses.Response")
}

func init() { proto.RegisterFile("proto/gethouses/gethouses.proto", fileDescriptor_637ed9c2c55ea129) }

var fileDescriptor_637ed9c2c55ea129 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x8d, 0x35, 0xad, 0x19, 0x3d, 0x2d, 0x52, 0x82, 0x88, 0x0d, 0x39, 0x79, 0x5a, 0x41,
	0x7f, 0x81, 0x68, 0x50, 0x11, 0x4b, 0x59, 0xbd, 0x7a, 0xd8, 0xb6, 0x43, 0x14, 0xda, 0x6c, 0x9d,
	0x9d, 0x08, 0xfe, 0x0b, 0x6f, 0xfe, 0x5d, 0xc9, 0x64, 0x6b, 0x72, 0xd0, 0xdb, 0xbe, 0xf7, 0xed,
	0xb0, 0x6f, 0xde, 0xc2, 0x64, 0x43, 0x8e, 0xdd, 0x79, 0x89, 0xfc, 0xea, 0x6a, 0x8f, 0xbe, 0x3b,
	0x69, 0x21, 0x6a, 0x5c, 0x3a, 0xbd, 0x7e, 0x5b, 0x90, 0xd3, 0x9e, 0x3e, 0xf4, 0x2d, 0xf2, 0x9d,
	0xd0, 0xfc, 0x3b, 0x82, 0x91, 0xc1, 0xf7, 0x1a, 0x3d, 0xab, 0x31, 0x0c, 0xaf, 0x08, 0xed, 0xfd,
	0x32, 0x8d, 0xb2, 0xe8, 0x2c, 0x31, 0x41, 0xa9, 0x13, 0x48, 0x9e, 0xd8, 0x12, 0xdf, 0x58, 0xc6,
	0x74, 0x57, 0x50, 0x67, 0xa8, 0x14, 0x46, 0x45, 0xb5, 0x14, 0x36, 0x10, 0xb6, 0x95, 0x32, 0x87,
	0x2b, 0x5c, 0xf0, 0x03, 0x7e, 0xa6, 0x7b, 0x61, 0x6e, 0x6b, 0xa8, 0x53, 0x80, 0x99, 0x2d, 0x71,
	0x5a, 0xaf, 0xe7, 0x48, 0x69, 0x2c, 0xb8, 0xe7, 0xe4, 0x5f, 0x11, 0xec, 0x1b, 0xf4, 0x1b, 0x57,
	0x79, 0x54, 0x47, 0x10, 0x17, 0x44, 0x53, 0x17, 0x92, 0xb5, 0xa2, 0x09, 0x5c, 0x10, 0x3d, 0xfa,
	0x32, 0xa4, 0x0a, 0xaa, 0xf1, 0xdb, 0xf5, 0x24, 0xd1, 0xa1, 0x09, 0x4a, 0x65, 0x70, 0x70, 0x5d,
	0x13, 0x61, 0xc5, 0xcd, 0x3b, 0x12, 0x69, 0x60, 0xfa, 0x56, 0x13, 0xf9, 0xd9, 0xb1, 0x5d, 0x09,
	0x8f, 0x85, 0x77, 0xc6, 0xc5, 0x0b, 0x24, 0xbf, 0xcd, 0xa9, 0x59, 0x5f, 0x4c, 0xf4, 0xdf, 0xfd,
	0xea, 0xd0, 0xed, 0x71, 0xf6, 0xff, 0x85, 0x76, 0xc5, 0x7c, 0x67, 0x3e, 0x94, 0xaf, 0xba, 0xfc,
	0x09, 0x00, 0x00, 0xff, 0xff, 0x43, 0xd0, 0x4b, 0xde, 0xcd, 0x01, 0x00, 0x00,
}
